# Generated by Django 5.0.6 on 2024-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.CharField(default='http://www.google.com', max_length=500),
            preserve_default=False,
        ),
    ]
